######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 25 16:04:50 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FindDialog.h MainWindow.h
SOURCES += FindDialog.cpp main.cpp MainWindow.cpp
